version: 2

project_name: ssher

before:
  hooks:
    - go mod tidy

builds:
  - id: ssher
    main: .
    binary: ssher
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/johnniewhite/ssher/cmd.Version={{.Version}}

archives:
  - id: ssher
    name_template: "{{ .ProjectName }}_{{ title .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

brews:
  - name: ssher
    repository:
      owner: johnniewhite
      name: homebrew-ssher
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/johnniewhite/ssher"
    description: "Ultimate SSH configuration manager + sshpass replacement"
    license: "MIT"
    install: |
      bin.install "ssher"
    test: |
      system "#{bin}/ssher --version"

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: johnniewhite
    name: ssher
  draft: true
