package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/johnniewhite/ssher/internal/store"
	"github.com/johnniewhite/ssher/internal/ui"
)

var (
	exportCfgOutput string
	exportCfgAppend bool
)

var exportConfigCmd = &cobra.Command{
	Use:   "export-config",
	Short: "Export servers as ~/.ssh/config-style entries",
	Long: `Generates an OpenSSH client_config snippet from the saved servers.

By default writes to stdout. With --output <path>, writes to that file.
With --append, appends to the file (or stdout) instead of overwriting.

Passwords are not exported — OpenSSH config has no notion of stored passwords,
so those servers will fall back to the system's normal SSH auth flow.`,
	RunE: func(c *cobra.Command, args []string) error {
		saved, err := ui.LoadVault()
		if err != nil {
			return err
		}
		text := renderSSHConfig(saved.Vault.SortedServers())

		switch {
		case exportCfgOutput == "":
			_, err = fmt.Print(text)
			return err
		case exportCfgAppend:
			f, err := os.OpenFile(exportCfgOutput, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o600)
			if err != nil {
				return err
			}
			defer f.Close()
			if _, err := fmt.Fprint(f, text); err != nil {
				return err
			}
			fmt.Println(ui.Successf(fmt.Sprintf("appended to %s", exportCfgOutput)))
		default:
			if err := os.MkdirAll(filepath.Dir(exportCfgOutput), 0o700); err != nil {
				return err
			}
			if err := os.WriteFile(exportCfgOutput, []byte(text), 0o600); err != nil {
				return err
			}
			fmt.Println(ui.Successf(fmt.Sprintf("wrote %s", exportCfgOutput)))
		}
		return nil
	},
}

func init() {
	exportConfigCmd.Flags().StringVarP(&exportCfgOutput, "output", "o", "", "write to FILE instead of stdout")
	exportConfigCmd.Flags().BoolVar(&exportCfgAppend, "append", false, "append to FILE instead of overwriting")
	rootCmd.AddCommand(exportConfigCmd)
}

func renderSSHConfig(servers []store.Server) string {
	var b strings.Builder
	b.WriteString("# Generated by ssher\n\n")
	for _, s := range servers {
		fmt.Fprintf(&b, "Host %s\n", s.Name)
		fmt.Fprintf(&b, "    HostName %s\n", s.Host)
		fmt.Fprintf(&b, "    User %s\n", s.User)
		if s.Port != 0 && s.Port != 22 {
			fmt.Fprintf(&b, "    Port %d\n", s.Port)
		}
		if s.AuthType == store.AuthKey && s.KeyPath != "" {
			fmt.Fprintf(&b, "    IdentityFile %s\n", s.KeyPath)
		}
		if s.JumpHost != "" {
			fmt.Fprintf(&b, "    ProxyJump %s\n", s.JumpHost)
		}
		if s.X11Forward {
			fmt.Fprintf(&b, "    ForwardX11 yes\n")
		}
		if s.KeepAlive > 0 {
			fmt.Fprintf(&b, "    ServerAliveInterval %d\n", s.KeepAlive)
		}
		for _, fw := range s.LocalForwards {
			fmt.Fprintf(&b, "    LocalForward %d %s:%d\n", fw.LocalPort, fw.RemoteHost, fw.RemotePort)
		}
		for _, fw := range s.RemoteForwards {
			fmt.Fprintf(&b, "    RemoteForward %d %s:%d\n", fw.LocalPort, fw.RemoteHost, fw.RemotePort)
		}
		for k, v := range s.CustomOptions {
			fmt.Fprintf(&b, "    %s %s\n", k, v)
		}
		for _, alias := range s.Aliases {
			fmt.Fprintf(&b, "Host %s\n    HostName %s\n", alias, s.Name)
		}
		b.WriteByte('\n')
	}
	return b.String()
}
